### ISSUE TITLE
Simple XOR transformation not detected as self-inverse

### ISSUE THREAD

**Issue by michaeljgoodman** [OALabs/hashdb-ghidra#2]
The transformation string `X ^ 0x43013fcc /* XOR */` is to my knowledge a self-inverse transformation, where the inverse would be `X ^ 0x43013fcc /* XOR */`

When using this transformation string the "[HashDB] You lied. This transformation is not invertible. I fixed it for you." debug message shows up and the "transformation not invertible" checkbox is checked.

Perhaps worth checking if there is a casing or datatype mismatch between the original X value and the scriptengine output

**Comment by michaeljgoodman** [comment]
Update: this only appears to happen for select hashes.

For the hash, BB0E2724h, this error occurs
For the hash, 217487Bh, this does not occur

I added some print lines for verbosity, it appears that for the hash BB0E2724h, 'inverse' is calculated as -1156700380, which is different to the base hash decimal value of 3138266916

**Comment by michaeljgoodman** [comment]
When forcing the print to display the unsigned version of inverse and baseHash it prints "Comparing 35080315 to 35080315"
I believe this may be an issue with unsigned vs signed longs. Java does not have an "unsigned long" data type but it does have Long.toUnsignedString(Long yourValueHere) to produce the unsigned string form.

**Comment by huettenhain** [comment]
Indeed, the bug is easily reproduced in a JavaScript console:

![image](https://user-images.githubusercontent.com/11869704/139561841-10d308cb-3a77-40a8-92f8-bbe3b619d239.png)

This will be a matter of getting JavaScript under control I guess.

**Comment by huettenhain** [comment]
This should be fixed via 2feaae1; I'll close this out, but we can always open a new issue if more JavaScript woes come up.
